services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - LLM_SERVICE_URL=llm-srv:50051
    depends_on:
      - llm-srv
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  llm-srv:
    build:
      context: ./llm-srv
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    develop:
      watch:
        - action: rebuild
          path: ./llm-srv/requirements.txt
        - action: sync
          target: /app
          path: ./llm-srv
