version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - LLM_SERVICE_URL=llm-srv:50051
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - llm-srv

  llm-srv:
    build:
      context: ./llm-srv
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    volumes:
      - ./llm-srv:/app
