# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_srv/protos/edit_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm_srv/protos/edit_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!llm_srv/protos/edit_service.proto\x12\x04\x65\x64it\"\x1b\n\x0b\x45\x64itRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x0c\x45\x64itResponse\x12\x16\n\x0esuggested_edit\x18\x01 \x01(\t2>\n\x0b\x45\x64itService\x12/\n\x04\x45\x64it\x12\x11.edit.EditRequest\x1a\x12.edit.EditResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_srv.protos.edit_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDITREQUEST']._serialized_start=43
  _globals['_EDITREQUEST']._serialized_end=70
  _globals['_EDITRESPONSE']._serialized_start=72
  _globals['_EDITRESPONSE']._serialized_end=110
  _globals['_EDITSERVICE']._serialized_start=112
  _globals['_EDITSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
